# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the third-party NOTICE body from the installed environment.

Satisfies Apache-2.0 §4(d): a redistributed work must carry attribution for the
third-party components it bundles. The NOTICE lists each dependency with its
version and normalized license.
"""

from __future__ import annotations

from scripts.supply_chain.licenses import UNKNOWN, PackageLicense

_HEADER = """\
Context Ontology Accelerator
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

This product includes software developed by third parties, listed below with
their respective licenses. This file is generated by
`scripts/supply_chain/cli.py notice`; do not edit by hand.

Full license texts are available from each project's distribution and from the
SPDX license list (https://spdx.org/licenses/).

--------------------------------------------------------------------------------
Third-party components
--------------------------------------------------------------------------------
"""


def render_notice(packages: list[PackageLicense]) -> str:
    lines: list[str] = [_HEADER]
    for pkg in sorted(packages, key=lambda p: p.name.lower()):
        license_str = pkg.normalized if pkg.normalized != UNKNOWN else (pkg.raw_license or "see project")
        version = pkg.version or "unpinned"
        lines.append(f"- {pkg.name} ({version}) — {license_str}")
    lines.append("")
    return "\n".join(lines)
